name: flutter_map_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.0
  carousel_slider: ^4.0.0
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  json_serializable: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.11

flutter:

  uses-material-design: true

  assets:
    - assets/spots.json
    - assets/images/